### ISSUE TITLE
Create Reasonable Resource Requests and Limits for CHT-Core-4.x

### ISSUE THREAD

**Issue by henokgetachew** [medic/helm-charts#21]
Right now the pods don't have resource limits and resource requests specified. 

As a result we run into issues like [these](https://github.com/medic/cht-core/issues/9332) from time to time where the pods get evicted.

All pods need to specify sensible resource resource requests and resource constraints.

**Comment by henokgetachew** [comment]
Additional information from this [ticket](https://github.com/medic/medic-infrastructure/issues/1035#issuecomment-2318311890).

The resource limits applied in that test are (For the couchdb pods):

```
      containers:
      - name: cht-couchdb-1
        image: public.ecr.aws/medic/cht-couchdb:4.2.0
        resources:
          requests:
            cpu: "1800m"    # About 22.7% of node CPU
            memory: "7Gi"   # About 23.6% of node memory
          limits:
            cpu: "2500m"    # About 31.6% of node CPU
            memory: "9Gi"   # About 30.4% of node memory
```

It probably makes sense to make these values configurable via `values.yaml` since it should depend from machine to machine and users might decide to make them higher/lower based on their own needs.
